/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "partb.h"
#include <ctype.h>

char ** partb_prog_1(char *host, char *exec, int x, int y)
{
	CLIENT *clnt;
	//the struct we define in partb.x
	numbers  partb_1_arg;
	

#ifndef	DEBUG
	clnt = clnt_create (host, PARTB_PROG, PARTB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	//Sends the parameter to the server.
	partb_1_arg.x = x;
	partb_1_arg.y = y;
	strcpy(partb_1_arg.exec,exec);

	//takes the result and back to main part.
	return partb_1(&partb_1_arg, clnt);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	//takes the parameters.
	char *host;
	char *exec;
	char *result;
	int a;
    int b;

	if (argc < 4) {
		printf ("usage: %s blacbox outputfile localhost\n", argv[0]);
		exit (1);
	}
	exec = argv[1];
	FILE *file = fopen(argv[2], "a");
	host = argv[3];
	//asks for integers.
	scanf("%d %d", &a, &b);

	//sends the program.
	result = *partb_prog_1(host, exec, a, b);

	//writes results to the file.
	if(isdigit(result[0])==0 || result[0] != "-"){
		fprintf(file, "FAIL:\n");
		fprintf(file, "%s\n", result);		
	}
	else{
		fprintf(file, "SUCCESS:\n");
		fprintf(file, "%s\n", result);	
	}
	
exit (0);
}
