/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "partb.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <sys/types.h>
#include <string.h>

char ** partb_1_svc(numbers *argp, struct svc_req *rqstp)
{
    //necessary integers, buffers.
    int p2b[2], b2pforerr[2], b2pforout[2];
    pid_t pid;
    char writeBuffer[10000], readforerrBuffer[10000], readforoutBuffer[10000];
    //implementation of pipes.
    pipe(p2b);
    pipe(b2pforerr);
    pipe(b2pforout);

    pid = fork();
    
    if(pid == -1){
        fprintf(stderr, "fork() failed.\n");
        exit(-1);
    }
    //PARENT PROCESS
    if(pid > 0){
        close(p2b[0]);
        close(b2pforerr[1]);
        close(b2pforout[1]);

#ifndef RUN_EXEC
        int errbytes = -1; 
        int outbytes = -1;
        static char *result; 

        //writes arguments to pipe.
        sprintf(writeBuffer, "%d %d\n", argp->x, argp->y);
        write(p2b[1], writeBuffer, strlen(writeBuffer));

        //reads the result of blackbox
        errbytes = read(b2pforerr[0], readforerrBuffer, sizeof(readforerrBuffer));
        outbytes = read(b2pforout[0], readforoutBuffer, sizeof(readforoutBuffer));

        //returns the result to the server.
        if(outbytes > 0){
            result = readforoutBuffer;
        }
        else{
            result = readforerrBuffer;
        }
        return &result;  
#endif 
    }
    else{
        dup2(p2b[0], STDIN_FILENO);
        dup2(b2pforout[1], STDOUT_FILENO);
        dup2(b2pforerr[1], STDERR_FILENO);

        close(b2pforerr[0]);
        close(b2pforerr[1]);
        close(b2pforout[0]);
        close(b2pforout[1]);
        close(p2b[0]);
        close(p2b[1]);

#ifndef RUN_EXEC
        //runs given arguments in given path.
        int a;
        int b;
        execl(argp->exec, NULL);
        scanf("%d %d", &a, &b);
#endif        

    }
}
